In [ ]:
import pandas as pd
import os

In [ ]:
orders=pd.read_csv("/content/olist_orders_dataset.csv")

In [ ]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [ ]:
orders.shape

(99441, 8)

In [ ]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [ ]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [ ]:
orders.describe()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-08-02 12:06:07,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [ ]:
orders["order_id"].duplicated().sum()

np.int64(0)

In [ ]:
orders["order_id"].nunique()

99441

In [ ]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [ ]:
orders[[
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]].head()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [ ]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

In [ ]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [ ]:
orders.duplicated().sum()

np.int64(0)

In [ ]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [ ]:
missing_pct = orders.isnull().mean() * 100

missing_pct.sort_values(ascending=False)

order_delivered_customer_date    2.981668
order_delivered_carrier_date     1.793023
order_approved_at                0.160899
order_id                         0.000000
order_purchase_timestamp         0.000000
order_status                     0.000000
customer_id                      0.000000
order_estimated_delivery_date    0.000000
dtype: float64

In [ ]:
orders[orders["order_delivered_customer_date"].isna()]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [ ]:
orders[orders["order_delivered_carrier_date"].isna()]["order_status"].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [ ]:
customers = pd.read_csv("/content/olist_customers_dataset.csv")
order_items = pd.read_csv("/content/olist_order_items_dataset.csv")
payments = pd.read_csv("/content/olist_order_payments_dataset.csv")
products = pd.read_csv("/content/olist_products_dataset.csv")
reviews = pd.read_csv("/content/olist_order_reviews_dataset.csv")
sellers = pd.read_csv("/content/olist_sellers_dataset.csv")

In [ ]:
tables = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "products": products,
    "reviews": reviews,
    "sellers": sellers
}

for name, df in tables.items():
    print(name, df.shape)

customers (99441, 5)
orders (99441, 8)
order_items (112650, 7)
payments (103886, 5)
products (32951, 9)
reviews (99224, 7)
sellers (3095, 4)

In [ ]:
for name, df in tables.items():
    print("\n---", name, "---")
    print(df.columns.tolist())

--- customers ---
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

--- orders ---
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

--- order_items ---
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

--- payments ---
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

--- products ---
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

--- reviews ---
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

--- sellers ---
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

In [ ]:
print("Orders:", orders["order_id"].nunique())
print("Customers:", customers["customer_id"].nunique())
print("Order items:", order_items["order_id"].nunique())
print("Products:", products["product_id"].nunique())
print("Sellers:", sellers["seller_id"].nunique())

Orders: 99441
Customers: 99441
Order items: 98666
Products: 32951
Sellers: 3095

In [ ]:
missing_customers = ~orders["customer_id"].isin(customers["customer_id"])

print("Orders with missing customer:", missing_customers.sum())

Orders with missing customer: 0

In [ ]:
missing_products = ~order_items["product_id"].isin(products["product_id"])

print("Order items with missing product:", missing_products.sum())

Order items with missing product: 0

In [ ]:
items_per_order = (
    order_items.groupby("order_id")
    .size()
    .sort_values(ascending=False)
)

items_per_order.head(10)

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
9ef13efd6949e4573a18964dd1bbe7f5    15
428a2f660dc84138d969ccd69a0ab6d5    15
9bdc4d4c71aa1de4606060929dee888c    14
73c8ab38f07dc94389065f7eba4f297a    14
37ee401157a3a0b28c9c6d0ed8c3b24b    13
2c2a19b5703863c908512d135aa6accc    12
af822dacd6f5cff7376413c03a388bb7    12
dtype: int64

In [ ]:
items_per_order.value_counts().sort_index()

1     88863
2      7516
3      1322
4       505
5       204
6       198
7        22
8         8
9         3
10        8
11        4
12        5
13        1
14        2
15        2
20        2
21        1
Name: count, dtype: int64

In [ ]:
order_value = (
    order_items.groupby("order_id")
    .agg(
        product_value=("price", "sum"),
        freight_value=("freight_value", "sum"),
        item_count=("order_id", "count")
    )
    .reset_index()
)

order_value.head()

                           order_id  product_value  freight_value  item_count
0  00010242fe8c5a6d1ba2dd792cb16214          58.90          13.29           1
1  00018f77f2f0320c557190d7a144bdd3         239.90          19.93           1
2  000229ec398224ef6ca0657da4fc703e         199.00          17.87           1
3  00024acbcdf0a6daa1e931b038114c75          12.99          12.79           1
4  00042b26cf59d7ce69dfabb4e55b4fd9         199.90          18.14           1

In [ ]:
order_value.shape

(98666, 4)

In [ ]:
order_value.describe()

       product_value  freight_value    item_count
count   98666.000000   98666.000000  98666.000000
mean      137.754076      22.823562      1.141731
std       210.645145      21.650909      0.538452
min         0.850000       0.000000      1.000000
25%        45.900000      13.850000      1.000000
50%        86.900000      17.170000      1.000000
75%       149.900000      24.040000      1.000000
max     13440.000000    1794.960000     21.000000

In [ ]:
order_value["order_id"].duplicated().sum()

np.int64(0)

In [ ]:
orders_analysis = orders.merge(
    order_value,
    on="order_id",
    how="left"
)

In [ ]:
orders_analysis.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,product_value,freight_value,item_count
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,29.99,8.72,1.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,118.70,22.76,1.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,159.90,19.22,1.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,45.00,27.20,1.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,19.90,8.72,1.0

In [ ]:
orders_analysis.shape

(99441, 11)

In [ ]:
orders_analysis.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
product_value                     775
freight_value                     775
item_count                        775
dtype: int64

In [ ]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [ ]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [ ]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [ ]:
customer_info = customers[
    ["customer_id", "customer_unique_id", "customer_city", "customer_state"]
]

In [ ]:
orders_analysis = orders_analysis.merge(
    customer_info,
    on="customer_id",
    how="left"
)

In [ ]:
orders_analysis.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,product_value,freight_value,item_count,customer_unique_id,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,29.99,8.72,1.0,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,118.70,22.76,1.0,af07308b275d755c9edb36a90c618231,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,159.90,19.22,1.0,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,45.00,27.20,1.0,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,19.90,8.72,1.0,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP

In [ ]:
state_orders = (
    orders_analysis
    .groupby("customer_state")
    .agg(
        orders=("order_id", "nunique"),
        customers=("customer_unique_id", "nunique"),
        revenue=("product_value", "sum")
    )
    .sort_values("revenue", ascending=False)
)

state_orders.head(10)

                orders  customers     revenue
customer_state
SP               41746      40302  5202955.05
RJ               12852      12384  1824092.67
MG               11635      11259  1585308.03
RS                5466       5277   750304.02
PR                5045       4882   683083.76
SC                3637       3534   520553.34
BA                3380       3277   511349.99
DF                2140       2075   302603.94
GO                2020       1952   294591.95
ES                2033       1964   275037.31

In [ ]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [ ]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [ ]:
payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [ ]:
order_payments = (
    payments.groupby("order_id")
    .agg(
        payment_value=("payment_value", "sum"),
        payment_installments=("payment_installments", "max"),
        payment_count=("payment_type", "count")
    )
    .reset_index()
)

In [ ]:
order_payments["order_id"].duplicated().sum()

np.int64(0)

In [ ]:
orders_analysis = orders_analysis.merge(
    order_payments,
    on="order_id",
    how="left"
)

In [ ]:
orders_analysis.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,product_value,freight_value,item_count,customer_unique_id,customer_city,customer_state,payment_value,payment_installments,payment_count
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,29.99,8.72,1.0,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,38.71,1.0,3.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,118.70,22.76,1.0,af07308b275d755c9edb36a90c618231,barreiras,BA,141.46,1.0,1.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,159.90,19.22,1.0,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,179.12,3.0,1.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,45.00,27.20,1.0,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN,72.20,1.0,1.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,19.90,8.72,1.0,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP,28.62,1.0,1.0

In [ ]:
payment_method_analysis = (
    payments.groupby("payment_type")
    .agg(
        orders=("order_id", "nunique"),
        payment_value=("payment_value", "sum")
    )
    .sort_values("payment_value", ascending=False)
)

payment_method_analysis

              orders  payment_value
payment_type
credit_card    76505    12542084.19
boleto         19784     2869361.27
voucher         3866      379436.87
debit_card      1528      217989.79
not_defined        3           0.00

In [ ]:
orders_analysis["payment_value"].mean()

np.float64(160.9902666934835)

In [ ]:
unique_customers = orders_analysis["customer_unique_id"].nunique()

print("Unique customers:", unique_customers)

Unique customers: 96096

In [ ]:
customer_orders = (
    orders_analysis
    .groupby("customer_unique_id")
    .agg(
        order_count=("order_id", "nunique"),
        total_spent=("payment_value", "sum")
    )
    .reset_index()
)

In [ ]:
customer_orders["customer_type"] = customer_orders["order_count"].apply(
    lambda x: "Repeat" if x > 1 else "One-time"
)

In [ ]:
customer_orders["customer_type"].value_counts()

customer_type
One-time    93099
Repeat       2997
Name: count, dtype: int64

In [ ]:
repeat_percentage = (
    (customer_orders["customer_type"] == "Repeat").mean() * 100
)

print(f"Repeat customer rate: {repeat_percentage:.2f}%")

Repeat customer rate: 3.12%

In [ ]:
top_customers = (
    customer_orders
    .sort_values("total_spent", ascending=False)
    .head(10)
)

top_customers

,customer_unique_id,order_count,total_spent,customer_type
3826,0a0a92112bd4c708ca5fde585afaa872,1,13664.08,One-time
26456,46450c74a0d8c5ca9395da1daac6c120,3,9553.02,Repeat
81962,da122df9eeddfedc1dc1f5349a1a690c,2,7571.63,Repeat
44447,763c8b1c9c68a0229c42c9fc6f662b93,1,7274.88,One-time
82808,dc4802a71eae9be1dd28f5d788ceb526,1,6929.31,One-time
26205,459bef486812aa25204be022145caa62,1,6922.21,One-time
95806,ff4159b92c40ebe40454e3e6a7c35ed6,1,6726.66,One-time
24121,4007669dec559734d6f53e029e360987,1,6081.54,One-time
35070,5d0a2980b292d049061542014e8960bf,1,4809.44,One-time
89688,eebb5dda148d3893cdaf5b5ca3040ccb,1,4764.34,One-time

In [ ]:
delivery_analysis = orders_analysis.copy()

In [ ]:
delivery_analysis["delivery_days"] = (
    delivery_analysis["order_delivered_customer_date"]
    - delivery_analysis["order_purchase_timestamp"]
).dt.total_seconds() / (60 * 60 * 24)

In [ ]:
delivery_analysis["delivery_days"].describe()

count    96476.000000
mean        12.558702
std          9.546530
min          0.533414
25%          6.766403
50%         10.217755
75%         15.720327
max        209.628611
Name: delivery_days, dtype: float64

In [ ]:
delivery_analysis["late_delivery"] = (
    delivery_analysis["order_delivered_customer_date"]
    > delivery_analysis["order_estimated_delivery_date"]
)

In [ ]:
delivery_analysis["late_delivery"].value_counts()

late_delivery
False    91614
True      7827
Name: count, dtype: int64

In [ ]:
late_rate = delivery_analysis["late_delivery"].mean() * 100

print(f"Late delivery rate: {late_rate:.2f}%")

Late delivery rate: 7.87%

In [ ]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [ ]:
review_data = reviews[
    ["order_id", "review_score"]
]

In [ ]:
delivery_analysis = delivery_analysis.merge(
    review_data,
    on="order_id",
    how="left"
)

In [ ]:
delivery_analysis[
    ["order_id", "delivery_days", "late_delivery", "review_score"]
].head(10)

,order_id,delivery_days,late_delivery,review_score
0,e481f51cbdc54678b7cc49136f2d6af7,8.436574,False,4.0
1,53cdb2fc8bc7dce0b6741e2150273451,13.782037,False,4.0
2,47770eb9100c2d0c44946d9cf07ec65d,9.394213,False,5.0
3,949d5b44dbf5de918fe9c16f97b45f8a,13.208750,False,5.0
4,ad21c59c0840e6cb83a9ceb5573f8159,2.873877,False,5.0
5,a4591c265e18cb1dcee52889e2d8acc3,16.542245,False,4.0
6,136cce7faa42fdb2cefd53fdc79a6098,NaN,False,2.0
7,6514b8ad8028c9f2cc2374ded245783f,9.989826,False,5.0
8,76c6e866289321a7c93b82b54852dc33,9.818762,False,1.0
9,e69bfb5eb88e0ed6a785585b27e16dbf,18.221852,False,5.0

In [ ]:
delivery_analysis.groupby("late_delivery")["review_score"].mean()

late_delivery
False    4.214307
True     2.566550
Name: review_score, dtype: float64

In [ ]:
delivery_analysis.groupby("review_score")["delivery_days"].mean()

review_score
1.0    21.311419
2.0    16.660580
3.0    14.261962
4.0    12.312356
5.0    10.688605
Name: delivery_days, dtype: float64